### ISSUE TITLE
java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool while executing jar in command line 

### ISSUE THREAD

**Issue by umeshshende** [OpenHFT/Java-Runtime-Compiler#52] opened 2020-09-27 17:17 UTC
I have an app that taking name(excel sheet) from user and I use those name as method and compile at runtime it's working in eclipse when running the project (not from command line ) but getting  java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool exception when running batch file containing command for executing jar file(which has logic for runtime compilation )  I have try with the added dependency in maven com.sun artifact mentioned in the issue but did not work any suggestions

**Comment by dpisklov** [comment] 2020-09-27 20:59
Duplicate of https://github.com/OpenHFT/Java-Runtime-Compiler/issues/46

**Closed by dpisklov** 2020-09-27 20:59 UTC

**Comment by umeshshende** [comment] 2020-09-28 08:34
#46  i have gone through the solution but JDK already installed in my local machine executing jar file local machine(Window 10)
but still getting
**Error** 
Reading main index file.....
Envoirement value of folderName :20200928_135704
Reading main index file finish
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.AssertionError: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
        at net.openhft.compiler.CompilerUtils.reset(CompilerUtils.java:85)
        at net.openhft.compiler.CompilerUtils.<clinit>(CompilerUtils.java:69)
        at tide.utility.Automation.compile(Automation.java:176)
        at tide.utility.Automation.Generate(Automation.java:114)
        at appstart.TestNgRunner.main(TestNgRunner.java:22)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at net.openhft.compiler.CompilerUtils.reset(CompilerUtils.java:81)
        ... 4 more

**Batch File**
cd
start cmd.exe /k java -jar fullPack.jar "Node01"

Can you please assist me?

**Comment by dpisklov** [comment] 2020-09-28 13:01
Are you using CompilerUtils.addClassPath as suggested in comments in #46?

**Comment by umeshshende** [comment] 2020-09-28 16:22
Yes but same result 
`try {
			String fileContents = getMethodString(newClassName);
			CompilerUtils.addClassPath("C:\\Program Files\\Java\\jdk1.8.0_241\\lib\\tools.jar");
			CompilerUtils.CACHED_COMPILER.loadFromJava(className, fileContents);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return false;
		}
		return true;`
While exception is being getting from this 
`    private static void reset() {
        s_compiler = ToolProvider.getSystemJavaCompiler();
        if (s_compiler == null) {
            try {
                Class<?> javacTool = Class.forName("com.sun.tools.javac.api.JavacTool");
                Method create = javacTool.getMethod("create");
                s_compiler = (JavaCompiler) create.invoke(null);
            } catch (Exception e) {
                throw new AssertionError(e);
            }
        }
    }`

**Comment by dpisklov** [comment] 2020-09-28 21:19
Well I don't know what can be wrong on Windows - no one over here uses that parody on the OS... But may be you need to check if:

* The path you specified indeed exists (correct version, accessible etc)
* Try using *nix-style path, i.e. `"C:/Program files/..."`
* Instead of `CompilerUtils#addClassPath()` try adding tools.jar to the classpath
* If nothing helps post here proper stack trace and reproducible example, although we will only be able to reproduce it on Linux.

**Comment by dpisklov** [comment] 2020-09-29 15:40
Well the accepted solution on Stackoverflow is the correct one. Copying a jar is a hack, not a proper solution. Proper solution is to set your `JAVA_HOME` to point to JDK folder and to correct your `PATH` to use java from the `$JAVA_HOME/bin`, as currently it clearly uses the JVM and not JDK.

**Comment by umeshshende** [comment] 2020-09-29 16:39
But another issue is target machine has JDK 14 but in my local machine is jdk8 so it's working but for JDK 14 I need upgrade the version but tool.jar is removed in jdk14 any suggestions on this

**Comment by dpisklov** [comment] 2020-09-29 17:41
We don't support Java 14. We only support LTS versions of Java, with latest
being Java 11 and next being Java 17.

**Comment by umeshshende** [comment] 2020-09-30 13:06
That mean package will not on java 14 ? any alternative suggestion?

**Comment by dpisklov** [comment] 2020-09-30 13:45
Actually tools.jar was removed in Java 9, but this project works fine with Java 9 and Java 11. Which means if instead of hacking things by copying jars you do it properly by fixing the JAVA_HOME and PATH, it will work fine. See e.g. [here](https://stackoverflow.com/questions/52638550/what-is-tools-jar-replacement) for details on tools.jar

**Comment by umeshshende** [comment] 2020-09-30 15:14
Ok thank you.
